config/routes.rb
Rails.application.routes.draw do
  get 'sample/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sample_controller.rb
class SampleController < ApplicationController
  @@max         = 0
  @@values      = []
  @@values_done = []
  def index
    if params[:max].present?
      @@max = params[:max].to_i
      @value = "Start from #{@@max}"
      @@values = (1..@@max).to_a.shuffle
      @@values_done = []
    else
      @value = @@values.shift
      @@values_done << @value
    end
    @values_done = @@values_done
    @max = @@max
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wanwan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sample/index.html.slim
.navbar.navbar-default
  .container-fluid
    .navbar-header
      a.navbar-brand BINGO!

table.table.table-bordered
  - (1..@max).to_a.each_slice(10) do |datas|
    tr
    - datas.each do |data|
      - c = 'active' if @values_done.include?(data)
      - c = 'success' if @value.to_i == data
      td[class="#{c}"] = data
=>link_to "NEXT", sample_index_path, class: "btn btn-success btn-block"
br
br
br
br
br
- for n in (1..7)
  - v = n * 10
  =>link_to "RESET #{v}", sample_index_path(max: v)
  br